spring.application.name=nmdc
spring.datasource.url=jdbc:mysql://localhost:3306/nextmovedancech57
spring.datasource.username=root
spring.datasource.password=valeria5

#create create-drop update validate
spring.jpa.hibernate.ddl-auto=update